name: ap.programming
on:
  push:
  release:
    types:
      - created
jobs:
  build-no-release:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      with:
        release-type: ruby
        package-name: jekyll-rushed-analytics
        # bump-minor-pre-major: true
        version-file: "jekyll-rushed-analytics"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.7
    - run: bundle install
    - name: Publish to GPR
      if: ${{ steps.release.outputs.release_created }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
    - name: Publish to RubyGems
      if: ${{ steps.release.outputs.release_created }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBY_GEM_SEC}}"
