name: ap.programming
on: [push, release]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: jekyll-rushed-analytics
          # bump-minor-pre-major: true
          version-file: "jekyll-rushed-analytics.gemspec"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.x
        if: ${{ steps.release.outputs.release_created }}
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      - name: "publish gem"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          echo "---\n:rubygems_api_key: $key\n""
          gem build jekyll-rushed-analytics.gemspec
          bash -c "$push1 $push2 $push3"
        env:
          key: ap-automator.RUBY_GEM_SEC
          push1: 'gem push --key github'
          push2: '--host https://rubygems.pkg.github.com/ap-automator'
          push3: 'jekyll-rushed-analytics.gemspec-*.gem'
