name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        gem install rake
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
  Publish code coverage:
    needs: build
    run: |
      export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
  coverage:
    name: test coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 659c18a493d41d369ac7c918305f9d8cfe8686c743db6ccec12d807547397dd8
      with:
        coverageCommand: bundle exec rake
